### ISSUE TITLE
Put preview in a window or in a split window

### ISSUE THREAD

**Issue by cheiff** [Andr3as/Codiad-MarkdownPreview#1]
Hi,
just wanted to know how difficult would it be to have this preview (and/or the html preview) in a pop up /modal window or even better in a split window instead of opening a new window.
Have you thinked of this already? Any clue where could I link this:
https://github.com/Codiad/Codiad/wiki/Plugin-Snippets#displaying-a-dialog-window-in-your-plugin
with your plugin?
Thanks, regards

**Comment by Andr3as** [comment]
I have currently no plans to change the preview to a modal. If you like to do this for your own you have to edit several lines:
- Change [this line](https://github.com/Andr3as/Codiad-MarkdownPreview/blob/master/init.js#L149) to `codiad.modal.load(600, _this.path+"preview.html");`
- Change the [template.js](https://github.com/Andr3as/Codiad-MarkdownPreview/blob/master/template.js) and [template.html](https://github.com/Andr3as/Codiad-MarkdownPreview/blob/master/template.html) to [Github gist](https://gist.github.com/Andr3as/bfee6e814b6b2989a1a1)
- The last files you have to change are markdown.css and github.css and change body to `#markdown_preview_modal` and insert before each rule `#markdown_preview_modal` to change the scope of each rule.
- Maybe you have to change `Codiad-MarkdownPreview` to your installation folder of MarkdownPreview

I didn't test it, but I think that should work. If you have any further question feel free to ask.

**Comment by cheiff** [comment]
Thanks a lot, I will test it as soon as possible and come back (I was on holidays...).

**Comment by Andr3as** [comment]
Check the new [LivePreview](https://github.com/Andr3as/Codiad-MarkdownPreview#livepreview)
